### ISSUE TITLE
Cannot install image_control in custom_nodes.

### ISSUE THREAD

**Issue by LaughterOnWater** [abyz22/image_control#1]
Win10, 64GB RAM, 3090

When I load sample.json, I get a no reaction from ComfyUI.
When loading the sample.png, I get this:

Used ComfyUI Manager to load everything.

Reboot ComfyUI.

I didn't see image_control in the standard set of controls on the manager, so I used the Git URL method. That failed.

When reloading the sample.png file, I get this in red:

When loading the graph, the following node types were not found:
abyz22_blend_onecolor
abyz22_drawmask
abyz22_makecircles
abyz22_smallhead
abyz22_blendimages
abyz22_lamaInpaint
abyz22_Frompipe
abyz22_ImpactWildcardEncode_GetPrompt
abyz22_Topipe
abyz22_lamaPreprocessor
abyz22_Padding Image
abyz22_Editpipe
Nodes that have failed to load will show as red on the graph.

What have I done wrong?

**Comment by abyz22** [comment]
After dragging sample.png, did you try installing it with ‘install missing custom nodes’ in comfyui Manager??

Or was the comfyUI_abyz22 folder created in the comfyui/custom_nodes path??

If it is created, can you write the console message that appears after turning off and turning on comfyui?

**Comment by abyz22** [comment]
i update requirements.txt,
try again
